### ISSUE TITLE
Sample Preview in File Browser

### ISSUE THREAD

**Issue by jsmith** [dawg/vusic#11]
Right now, we have a working file explorer but lack the needed functionality for the DAW.

1. We should filter files based on its extension so we only show audio files.
2. We should support up/down/right/left arrow key navigation similar to IDEs.
3. When an audio file is focused on, we should automatically play the sample.

Additionally, the UI should probably be improved!

**Comment by aeldesoky** [comment]
- [ ] We should filter files based on its extension so we only show audio files.

- [ ] We should support up/down/right/left arrow key navigation similar to IDEs.

- [ ] When an audio file is focused on, we should automatically play the sample.

- [ ] Drag & drop audio files to playlist and sample tab

- [ ] Double clicking an audio file automatically opens the file in the sample tab

- [ ] Drag & drop files to the project from outside the application (Low Priority)
